### PR TITLE
Update README.md by changed Usage and adjusted all links

### PR DESCRIPTION
**Pull request by jokittipong**
Update readme by changed Usage and adjusted all links

### CODE REVIEW

**Comment by jokittipong** [comment]
@sho-i98  @Nicole-Tu97  I need some helps on the README.md that I need the input for running analysis.
If you two already done it, please tell me. I will added the running analysis part and will add, commit, push and will pull request for you two to review it in one go.

Sorry for my previous pull request. It's better to finish it completely and will ask you two to review it only once.

**Comment by Nicole-Tu97** [comment]
I finished the scripts files and tested them locally in my computer. All works, except for the fit_polynomial_regression.py I cannot rerun after my frist successful run. Please take a look to see if they works on your local computer!

**Comment by jokittipong** [comment]
Hi All, I'm back with the completed README.md now.
Please check and approve it for me!!!!!!

**Review by sho-i98 — APPROVED** [review]
Checked, thank you!

**Pull request merged**
